### PR TITLE
Fixed stopping of service, daemon and CLI

### LINKED ISSUE #443: Tequilapi "/stop" endpoint does not stop `myst service`
**How to reproduce:**
1. Start service
```
bin/build && bin/run service --agreed-terms-and-conditions
```
2. Try to stop service thru Tequilapi 
```
curl -X POST http://localhost:4050/stop

2018-10-14T11:53:15.974989 [Info] Application stop requested
2018-10-14T11:53:15.975132 [Info] [discovery] stopping discovery loop..
2018-10-14T11:53:15.975173 [Info] [discovery] cancelled identity registration
2018-10-14T11:53:15.975235 [Info] [service-manager] Waiting for service to finish
2018-10-14T11:53:15.986791 [Info] [nat] NAT rules cleared
2018-10-14T11:53:15.994995 [Info] [nat] IP forwarding disabled
2018-10-14T11:53:15.995061 [Info] [client-management] Shutdown
2018-10-14T11:53:15.995242 [Info] [client-management] Shutdown finished
2018-10-14T11:53:15.995282 [Info] No active connection - proceeding
2018-10-14T11:53:15.995419 [Trace] [openvpn-process] Stdout: Sun Oct 14 14:53:15 2018 event_wait : Interrupted system call (code=4)
2018-10-14T11:53:15.995481 [Info] Api stopped
Good bye
```
3. **Result1 (random):** Process does not stop and After 3s or some time service outputs again
```
2018-10-14T11:53:18.001838 [Trace] [openvpn-process] Stdout: Sun Oct 14 14:53:18 2018 Closing TUN/TAP interface
2018-10-14T11:53:18.003133 [Debug] [client-management] Line received: >STATE:1539517998,EXITING,SIGINT,,,,,
2018-10-14T11:53:18.003184 [Warn] [client-management] Connection failed to read. EOF
2018-10-14T11:53:18.003212 [Trace] [client-management] Line delivering: >STATE:1539517998,EXITING,SIGINT,,,,,
2018-10-14T11:53:18.003374 [Info] [client-management] Event consumer is done
2018-10-14T11:53:18.003431 [Info] [service-openvpn] Openvpn service exited
2018-10-14T11:53:18.003527 [Warn] [client-management] Middleware stop error. connection is gone
2018-10-14T11:53:18.003653 [Trace] [openvpn-process] Stdout: Sun Oct 14 14:53:18 2018 SIGINT[hard,] received, process exiting
2018-10-14T11:53:18.003667 [Trace] [openvpn-process] Stdout: Sun Oct 14 14:53:18 2018 MANAGEMENT: >STATE:1539517998,EXITING,SIGINT,,,,,
2018-10-14T11:53:18.005274 [Info] [openvpn-process] Stderr: stream ended
2018-10-14T11:53:18.005322 [Info] [openvpn-process] Stdout: stream ended
```

4. **Result2 (random):** Process exists:
```
2018-10-14T11:52:46.419441 [Info] Application stop requested
2018-10-14T11:52:46.433123 [Info] [nat] NAT rules cleared
2018-10-14T11:52:46.441483 [Info] [nat] IP forwarding disabled
2018-10-14T11:52:46.441541 [Info] No active connection - proceeding
2018-10-14T11:52:46.441692 [Info] Api stopped
Good bye
2018-10-14T11:52:46.44769 [Info] [nat] NAT rules cleared
2018-10-14T11:52:46.447734 [Warn] Failed to disable IP forwarding: [/usr/sbin/sysctl -w net.inet.ip.forwarding=0] Returned exit error: exec: Stdout already set Cmd output:
2018-10-14T11:52:46.447789 [Info] [nat] IP forwarding disabled
2018-10-14T11:52:46.447922 [Info] No active connection - proceeding
2018-10-14T11:52:46.447985 [Info] Api stopped
```

**Expected result:**
- **Result2** should be stable, not random
- **Result2** should have only 1 log message "Api stopped"

### PR DESCRIPTION
**Pull request by soffokl**
Closes #443

### CODE REVIEW

File: cmd/commands/service/command.go [hunk 1]
```diff
@@ -101,7 +100,7 @@ func NewCommand(licenseCommandName string) *cli.Command {
 				errorChannel <- di.ServiceManager.Wait()
 			}()
 
-			cmd.RegisterSignalCallback(utils.SoftKiller(di.Shutdown))
+			cmd.RegisterSignalCallback(func() { errorChannel <- nil })
```
Comment (Waldz) [inline cmd/commands/service/command.go]: Why do we need dummy stopper at all?

File: cmd/commands/cli/command.go [hunk 2]
```diff
@@ -38,6 +39,7 @@ const cliCommandName = "cli"
 // NewCommand constructs CLI based Mysterium UI with possibility to control quiting
 func NewCommand() *cli.Command {
 	var di cmd.Dependencies
+	cmdCLI := &cliApp{}
```
Comment (Waldz) [inline cmd/commands/cli/command.go]: Dont need to init:
`var cmdCLI *cliApp`

File: cmd/commands/service/command.go (hunk 1 above)
Comment (soffokl) [reply cmd/commands/service/command.go]: It's not dummy stopper. 

We need to have a graceful shutdown for the command. 
This handler returns `nil` error to stop the function, since it's expected behavior for the signals.

File: cmd/commands/daemon/command.go [hunk 3]
```diff
@@ -32,11 +31,15 @@ func NewCommand() *cli.Command {
...
 		Action: func(ctx *cli.Context) error {
+			errorChannel := make(chan error, 1)
 			if err := di.Bootstrap(cmd.ParseFlagsNode(ctx)); err != nil {
 				return err
 			}
-			cmd.RegisterSignalCallback(utils.SoftKiller(di.Shutdown))
-			return di.Node.Wait()
+			go func() { errorChannel <- di.Node.Wait() }()
+
+			cmd.RegisterSignalCallback(func() { errorChannel <- nil })
```
Comment (tadovas) [inline cmd/commands/daemon/command.go]: I see a channel of size 1 here, and two writes (from Node.Wait goroutine, and signaling goroutine), only one read. Another thing - when signal is received and Action exits (return <-errorChannel), what happens with Node which is still running? is it stopped somewhere else? doesn't sound right.

Comment (soffokl) [reply cmd/commands/daemon/command.go]: A node will be stopped by the `di.Shutdown()` in the `After` section, a bit lower.

Comment (soffokl) [reply cmd/commands/daemon/command.go]: Buffered channel is used here to not block goroutine and release it without waiting of reading.

Comment (tadovas) [reply cmd/commands/daemon/command.go]: My hint was maybe a channel with size 2 should be more appropriate? So each goroutine can put its result independenly whenever another party read previous value or not

File: cmd/commands/service/command.go (hunk 1 above)
Comment (Waldz) [reply cmd/commands/service/command.go]: clear now, but just after explanation :)

File: cmd/commands/cli/command.go (hunk 2 above)
Comment (Waldz) [reply cmd/commands/cli/command.go]: I meant - You should initiate full variable `&cliApp{}`, not only several attributes of it

Comment (soffokl) [reply cmd/commands/cli/command.go]: Unfortunately, fields of the `cliApp` depend on the variable that we are getting only from `ctx` in `Action` block.

File: cmd/commands/daemon/command.go (hunk 3 above)
Comment (soffokl) [reply cmd/commands/daemon/command.go]: Make sense, especially not only in this case but in other, with more waiters. 
Changed it in all places.

File: cmd/commands/cli/command.go [hunk 4]
```diff
@@ -38,29 +39,31 @@ const cliCommandName = "cli"
...
-				historyFile: filepath.Join(nodeOptions.Directories.Data, ".cli_history"),
-				tequilapi:   tequilapi_client.NewClient(nodeOptions.TequilapiAddress, nodeOptions.TequilapiPort),
-			}
+			cmdCLI.historyFile = filepath.Join(nodeOptions.Directories.Data, ".cli_history")
+			cmdCLI.tequilapi = tequilapi_client.NewClient(nodeOptions.TequilapiAddress, nodeOptions.TequilapiPort)
+
 			go func() { errorChannel <- cmdCLI.Run() }()
-			cmd.RegisterSignalCallback(utils.SoftKiller(cmdCLI.Kill))
-			cmd.RegisterSignalCallback(utils.SoftKiller(di.Shutdown))
+			cmd.RegisterSignalCallback(func() { errorChannel <- nil })
```
Comment (Waldz) [inline cmd/commands/cli/command.go]: Did You alligned change to this stop flow also:
`tequilapi_endpoints.AddRouteForStop(router, utils.SoftKiller(di.Shutdown))`

Comment (soffokl) [reply cmd/commands/cli/command.go]: Didn't get a question. 

In the [master](https://github.com/mysteriumnetwork/node/blob/master/core/node/node.go#L117) I see 
```
utils.SoftKiller(node.Kill)
```

So it will stop the `node` and service will be exited correctly, and `di.Shutdown()` will be applies from `After` section.
