### PR TITLE
Wait for valid registered identity before starting services

### LINKED ISSUE #1163: Node crashes/cli hangs if network unavailable on startup

### PR DESCRIPTION
**Pull request by tadaskay**
Fixes #1163

Functional changes:

- If initial proposal fetch fails, ignore it and continue (it will continuously attempt to fetch in a separate goroutine)
- Use [new discovery API endpoint](https://github.com/mysteriumnetwork/api/pull/138) to check if an existing identity is registered
- Proceed with node services startup only when the identity is valid and registered
  This also kind of solves 'app starting before the network is up' problem, since it will retry to get identity every 10s.
  To properly address network state issue, we should make separate node components react to network state events, but that's a 
  separate huge epic.

Additionally:

- Migrate "errors" to "github.com/pkg/errors" to retain stacktraces
- More error wraps
- Cut HTTP timeouts. _Note: leaving tequilapi timeout rather high, because of e2e test issues. Need to investigate further, perhaps containers are not yet healthy before running tests?_

### CODE REVIEW

File: cmd/commands/daemon/command.go [hunk 1]
```diff
@@ -18,6 +18,7 @@
 package daemon
 
 import (
+	"github.com/cihub/seelog"
```
Comment (soffokl) [inline cmd/commands/daemon/command.go]: We probably should use a new approach for logging that was merged yesterday.

File: cmd/commands/service/command.go [hunk 2]
```diff
@@ -131,13 +143,18 @@ func (sc *serviceCommand) Run(ctx *cli.Context) (err error) {
 	return <-sc.errorChannel
 }
 
-func (sc *serviceCommand) unlockIdentity(identityOptions service.OptionsIdentity) (*identity.Identity, error) {
-	id, err := sc.tequilapi.CurrentIdentity(identityOptions.Identity, identityOptions.Passphrase)
-	if err != nil {
-		return nil, err
-	}
+const retryRate = 10 * time.Second
```
Comment (soffokl) [inline cmd/commands/service/command.go]: Can we put the const on top of the file?

File: services/openvpn/core/options_node.go [hunk 3]
```diff
@@ -20,14 +20,15 @@ package core
 import (
 	"bufio"
 	"bytes"
-	"errors"
+
```
Comment (soffokl) [inline services/openvpn/core/options_node.go]: Extra line.

File: cmd/commands/service/command.go (hunk 2 above)
Comment (tadaskay) [reply cmd/commands/service/command.go]: Having it next to the code using it is easier to understand/discover, but I can move it.

Comment (tadaskay) [reply cmd/commands/service/command.go]: Moved it to the inside of the function. There's no need to expose it to package.

File: services/openvpn/discovery/dto/bandwidth_test.go [hunk 4]
```diff
@@ -19,10 +19,10 @@ package dto
 
 import (
 	"encoding/json"
-	"errors"
 	"testing"
 
 	"github.com/mysteriumnetwork/node/datasize"
+	assert2 "github.com/mysteriumnetwork/node/testkit/assert"
```
Comment (vkuznecovas) [inline services/openvpn/discovery/dto/bandwidth_test.go]: could we rename this to kitassert or something like this instead of the number two?

Comment (tadaskay) [reply services/openvpn/discovery/dto/bandwidth_test.go]: I'm not sure about this one. Is this critical?

File: identity/selector/handler.go [hunk 5]
```diff
@@ -71,15 +77,26 @@ func (h *handler) UseOrCreate(address, passphrase string) (id identity.Identity,
...
+		return id, errors.Wrap(err, "failed to unlock identity")
+	}
+
+	registered, err := h.registry.IdentityExists(id, h.signerFactory(id))
+	if err != nil {
+		return id, errors.Wrap(err, "failed to verify registration status of local identity")
+	}
+	if !registered {
+		log.Info("existing identity is not registered, attempting to register")
+		if err = h.registry.RegisterIdentity(id, h.signerFactory(id)); err != nil {
```
Comment (Waldz) [inline identity/selector/handler.go]: @zolia maybe it's time to drop identity registration at all - now it's a feature  identity stats collecting.
For Ethereum flow we can't just register identity, it's user flow, calling. For this flow user he will need to transfer money.

File: services/openvpn/discovery/dto/bandwidth_test.go (hunk 4 above)
Comment (tadaskay) [reply services/openvpn/discovery/dto/bandwidth_test.go]: Renamed `assert` package to `assertkit` to avoid clashes and import aliasing.

File: identity/selector/handler.go (hunk 5 above)
Comment (Waldz) [reply identity/selector/handler.go]: Actually we a calling `registry.RegisterIdentity()` just to make `SetPayoutInfo()` to be successful, then user calls it later.

Lets remake SetPayoutInfo(), so that it fixes it's DB records
