### PR TITLE
Fix identity tests

### LINKED ISSUE #1926: Flaky tests:  FAIL	github.com/mysteriumnetwork/node/identity
identity tests timeout once in a blue moon on CI.

{"level":"debug","time":"2020-03-26T13:19:46+01:00","message":"Using lightweight keystore"}
 {"level":"debug","time":"2020-03-26T13:20:20+01:00","message":"Caching unlocked address: 0x53a835143c0ef3bbcbfa796d7eb738ca7dd28f68"}
 {"level":"debug","time":"2020-03-26T13:20:20+01:00","message":"Published topic=\"identity-unlocked\" event=0x53a835143c0ef3bbcbfa796d7eb738ca7dd28f68"}
 {"level":"debug","time":"2020-03-26T13:20:20+01:00","message":"Using lightweight keystore"}
 {"level":"debug","time":"2020-03-26T13:20:27+01:00","message":"Published topic=\"identity-created\" event=0x000000000000000000000000000000000000beef"}
 {"level":"debug","time":"2020-03-26T13:20:27+01:00","message":"Using lightweight keystore"}
 FAIL	github.com/mysteriumnetwork/node/identity	60.873s

### PR DESCRIPTION
**Pull request by vkuznecovas**
The mock should behave like a 1:1 ethereum keystore, except avoid decryption and encryption of keys.

This means the memory and cpu footprint is decreased by a large factor.

Tests now consumer 7MB as compared to 4GB before hand, and complete a few hundred times faster.

Fixes #1926

### CODE REVIEW

File: identity/keystore_mock.go [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+
+var mockKeys = map[common.Address]MockKey{
+	common.HexToAddress("53a835143c0ef3bbcbfa796d7eb738ca7dd28f68"): MockKey{
+		PkHex: "6f88637b68ee88816e73f663aef709d7009836c98ae91ef31e3dfac7be3a1657",
+		Pass:  "",
+	},
+}
+
+// NewMockKeystore returns a new mock keystore
+func NewMockKeystore(keys map[common.Address]MockKey) *mockKeystore {
```
Comment (anjmao) [inline identity/keystore_mock.go:45]: Can we use eth `keystore.NewPlaintextKeyStore` instead of mock?

**Comment by zolia** [comment]
looks like tests are failing

File: identity/keystore_filesystem.go [hunk 2]
```diff
@@ -34,26 +35,46 @@ import (
...
+
 // NewKeystoreFilesystem create new keystore, which keeps keys in filesystem.
 func NewKeystoreFilesystem(directory string, lightweight bool) *Keystore {
-	var ks *ethKs.KeyStore
-	if lightweight {
+	var ks ks
+	var keyDecryptFunc func(keyjson []byte, auth string) (*ethKs.Key, error)
+
+	// In test scenarios, we'll skip the real ethereum keystore and prefer a memory one instead.
+	if flag.Lookup("test.v") != nil {
```
Comment (anjmao) [inline identity/keystore_filesystem.go:54]: This e2e test is failing https://github.com/mysteriumnetwork/node/blob/master/e2e/mobile_entrypoint_test.go as it needs real keystore. 

Maybe it's better to create separate func `NewKeystoreMock() *Keystore` and use it explicitly there needed.
