### PR TITLE
Extract validation phase to a separate component in connection manager

### LINKED ISSUE #1945: Wrong error message while trying to connect with unlocked identity
Consumer is provided with an error "insufficient balance" when in fact his identity is locked. 

daemon output: 

```bash
2020-03-29T14:15:26.552 INF tequilapi/endpoints/connection.go:229    > identity "0x0fc008021a33ee21a6d2c9dbb2a547fd8fc0b84a" is registered, continuing...
2020-03-29T14:15:26.730 ERR tequilapi/endpoints/connection.go:261    >  error="insufficient balance"
```

cli output
```bash
» connect 0x0fc008021a33ee21a6d2c9dbb2a547fd8fc0b84a 0x2bc8193504a60c1d9746006a9eb3ade5d6b7f51b wireguard
[CONNECTING] from: 0x0fc008021a33ee21a6d2c9dbb2a547fd8fc0b84a to: 0x2bc8193504a60c1d9746006a9eb3ade5d6b7f51b
2020-03-29T14:15:26.551 DBG config/config.go:185                     > Returning default value accountant.accountant-id:0x0214281cf15C1a66b51990e2E65e1f7b7C363318
2020-03-29T14:15:26.731 ERR tequilapi/client/http_client.go:113      >  error="server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/connection). Possible error: insufficient balance"
[WARNING] server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/connection). Possible error: insufficient balance

### PR DESCRIPTION
**Pull request by vkuznecovas**
Connection manager now has a separate component responsible for pre-flight checks.

Fixes #1945

### CODE REVIEW

File: core/connection/connection_validator_test.go [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+		proposal   market.ServiceProposal
+	}
+	tests := []struct {
+		name    string
+		fields  fields
+		args    args
+		wantErr error
+	}{
+		{
+			name:    "returns insuficient balance",
```
Comment (soffokl) [inline core/connection/connection_validator_test.go]:
```suggestion
			name:    "returns insufficient balance",
```

File: core/connection/connection_validator_test.go [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+			}
+		})
+	}
+}
+
+type mockUnlockChecker struct {
+	toReturn bool
+}
+
+func (muc *mockUnlockChecker) IsUnlocked(ID string) bool {
```
Comment (soffokl) [inline core/connection/connection_validator_test.go]: > captLocal: `ID' should not be capitalized (gocritic)
```suggestion
func (muc *mockUnlockChecker) IsUnlocked(id string) bool {
```

File: core/connection/connection_validator_test.go [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+	return muc.toReturn
+}
+
+type mockConsumerBalanceGetter struct {
+	toReturn uint64
+}
+
+func (mcbg *mockConsumerBalanceGetter) GetBalance(ID identity.Identity) uint64 {
```
Comment (soffokl) [inline core/connection/connection_validator_test.go]: > captLocal: `ID' should not be capitalized (gocritic)
```suggestion
func (mcbg *mockConsumerBalanceGetter) GetBalance(id identity.Identity) uint64 {
```
