### PR TITLE
Fix stability of native (userspace) provider

### LINKED ISSUE #5770: Crash of native provider
It happens rarely, once per 3 days or so, especially on unstable Wifi

```DEBUG: (myst) 2023/04/02 19:52:11 Device closing
2023-04-02T19:52:11.000 INF node\services\wireguard\service\stats_publisher.go:65 > Stopped publishing statistics for session ccf3ea93-aa73-41b6-9bff-a456254c42f0
DEBUG: (myst) 2023/04/02 19:52:11 peer(j2u2…QWkM) - Routine: sequential receiver - stopped
DEBUG: (myst) 2023/04/02 19:52:11 Routine: TUN reader - stopped
DEBUG: (myst) 2023/04/02 19:52:11 Routine: event worker - stopped
DEBUG: (myst) 2023/04/02 19:52:11 Routine: receive incoming v6 - stopped
DEBUG: (myst) 2023/04/02 19:52:11 Routine: receive incoming v4 - stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x7ff6afda0e47]

goroutine 11497548 [running]:
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectInbound(...)
        C:/Users/user/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/tcpip/link/channel/channel.go:194
github.com/mysteriumnetwork/node/services/wireguard/endpoint/netstack-provider.(*netTun).Write(0xc00202a700, {0xc00140d000, 0xc003b4cb60?, 0x7ff6b1762100?}, 0xc003ed9f88?)
        C:/Users/user/src/node/services/wireguard/endpoint/netstack-provider/netstack.go:164 +0x107
golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0xc002157c00)
        C:/Users/user/go/pkg/mod/github.com/zensey/wireguard-go@v0.0.0-20230310142505-f95bd75c0cb1/device/receive.go:475 +0x4e3
created by golang.zx2c4.com/wireguard/device.(*Peer).Start
        C:/Users/user/go/pkg/mod/github.com/zensey/wireguard-go@v0.0.0-20230310142505-f95bd75c0cb1/device/peer.go:191 +0x297
```

### PR DESCRIPTION
**Pull request by Zensey**
This is supposed to fix #5770.
Finally, with this version of wireguard-go userspace provider doesn't fail in ~7 days.
Will try to stress-test it using bad Wifi with interference.

### CODE REVIEW

File: services/wireguard/endpoint/netstack/netstack.go [hunk 1]
```diff
@@ -151,30 +152,37 @@ func (tun *netTun) Events() <-chan tun.Event {
...
-	case 6:
-		tun.ep.InjectInbound(header.IPv6ProtocolNumber, pkb)
+		pkb := stack.NewPacketBuffer(stack.PacketBufferOptions{Payload: bufferv2.MakeWithData(packet)})
+		switch packet[0] >> 4 {
+		case 4:
+			tun.ep.InjectInbound(header.IPv4ProtocolNumber, pkb)
+		case 6:
+			tun.ep.InjectInbound(header.IPv6ProtocolNumber, pkb)
+		default:
+			return 0, syscall.EAFNOSUPPORT
```
Comment (Snawoot) [inline services/wireguard/endpoint/netstack/netstack.go:183]: Will it build on Android? Is it portable?

Also there is a notice in syscall package documentation that it's already deprecated. Maybe we should approach this with some separate package which imports needed constant from x/sys?

**Review by Snawoot — COMMENTED** [review]
Can't say if it's okay or not to use constant from syscall package.

File: services/wireguard/endpoint/netstack/netstack.go (hunk 1 above)
Comment (Zensey) [reply services/wireguard/endpoint/netstack/netstack.go:183]: It will build. There's no problem with Android, the file syscall_linux.go it is used and constants are available. 
BTW wireguard-go code that constants are also used:
https://github.com/inverse-inc/wireguard-go/blob/master/conn/conn_default.go#L106

Comment (Snawoot) [reply services/wireguard/endpoint/netstack/netstack.go:183]: Okay, then shouldn't be a problem. Thanks!

**Review by Snawoot — APPROVED** [review]
