### PR TITLE
Fix freezing openvpn3 when connection is retried in loop

### LINKED ISSUE #682: Connecting to nodes always fail after canceling connection to node
To reproduce:
- Connect to working node - connection works
- Disconnect
- Connect to node which hangs on "Connecting" state
- Cancel connection
- Connect to working node (same as in 1st step) - connection hangs in "Connecting" state

Go ADB logs:

```
01-28 13:30:27.997 15113 15278 I GoLog   :
01-28 13:30:27.997 15113 15278 I GoLog   : 2019-01-28T11:30:27.996562 [Info] Unhandled event: {Fatal:false Error:false Name:WAIT Info:}
01-28 13:30:28.002 15113 15278 I GoLog   : 2019-01-28T11:30:28.001924 [Info] Log: Connecting to [185.156.81.61]:1194 (185.156.81.61) via UDPv4
01-28 13:30:28.002 15113 15278 I GoLog   :
01-28 13:30:30.539 15113 15229 I GoLog   : 2019-01-28T11:30:30.53877 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:30:31.430 15113 15278 I GoLog   : 2019-01-28T11:30:31.429512 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:30:38.008 15113 15278 I GoLog   : 2019-01-28T11:30:38.003439 [Info] Log: Server poll timeout, trying next remote entry...
01-28 13:30:38.008 15113 15278 I GoLog   :
01-28 13:30:38.010 15113 15278 I GoLog   : 2019-01-28T11:30:38.006745 [Info] Unhandled event: {Fatal:false Error:false Name:RECONNECTING Info:}
01-28 13:30:38.012 15113 15278 I GoLog   : 2019-01-28T11:30:38.009427 [Info] Log: Contacting 185.156.81.61:1194 via UDP
01-28 13:30:38.012 15113 15278 I GoLog   :
01-28 13:30:38.012 15113 15278 I GoLog   : 2019-01-28T11:30:38.010481 [Info] Unhandled event: {Fatal:false Error:false Name:WAIT Info:}
01-28 13:30:38.032 15113 15278 I GoLog   : 2019-01-28T11:30:38.031939 [Info] Log: Connecting to [185.156.81.61]:1194 (185.156.81.61) via UDPv4
01-28 13:30:38.032 15113 15278 I GoLog   :
01-28 13:30:40.560 15113 15278 I GoLog   : 2019-01-28T11:30:40.558472 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:30:41.307 15113 15278 I GoLog   : 2019-01-28T11:30:41.306606 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:30:50.600 15113 15229 I GoLog   : 2019-01-28T11:30:50.598146 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:30:51.344 15113 15229 I GoLog   : 2019-01-28T11:30:51.342047 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:31:00.562 15113 15236 I GoLog   : 2019-01-28T11:31:00.562139 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:31:01.532 15113 15258 I GoLog   : 2019-01-28T11:31:01.53114 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:31:10.573 15113 15280 I GoLog   : 2019-01-28T11:31:10.571586 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:31:11.390 15113 15236 I GoLog   : 2019-01-28T11:31:11.388412 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:31:11.927 15113 15278 I GoLog   : 2019-01-28T11:31:11.926566 [Info] [connection-manager] Cancelling connection initiation
01-28 13:31:11.936 15113 15278 I GoLog   : 2019-01-28T11:31:11.932917 [Debug] [NATS.Sender] Request '0xc327201bf626a50c0702f9b15915a4f2a6b1982c.0x869ec82817cc5df7e0a56be5bbf0476b08c12f20.session-destroy' se
nding: {"payload":{"session_id":"32561258-7332-4313-9d0d-185ff18acbb9"},"signature":"TCgMdrPuu6QJsY6/5oHm+OeYl4vynEzJ+Q4ARhpNXDFPC/+qx7U2APcO8Ghjs1Rfx9Ak1gSgTlnS7fiyYCqkvgA="}
01-28 13:31:13.942 15113 15278 I GoLog   : 2019-01-28T11:31:13.941652 [Info] [session.DestroyProducer] Session destroy request failed: "failed to send request '0xc327201bf626a50c0702f9b15915a4f2a6b1982c.0x8
69ec82817cc5df7e0a56be5bbf0476b08c12f20.session-destroy'. nats: timeout"
01-28 13:31:13.949 15113 15278 I GoLog   : 2019-01-28T11:31:13.947219 [Debug] [session-stats-sender] stopping
01-28 13:31:13.964 15113 15278 I GoLog   : 2019-01-28T11:31:13.963555 [Trace] [session-storage] Session 32561258-7332-4313-9d0d-185ff18acbb9 updated
01-28 13:31:14.215 15113 15225 I GoLog   : 2019-01-28T11:31:14.214771 [Info] [Mysterium.api] Session stats sent: 32561258-7332-4313-9d0d-185ff18acbb9
01-28 13:31:14.215 15113 15225 I GoLog   : 2019-01-28T11:31:14.214822 [Debug] [session-stats-sender] Final stats sent
01-28 13:31:20.648 15113 15280 I GoLog   : 2019-01-28T11:31:20.645474 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:31:20.859 15113 15280 I GoLog   : 2019-01-28T11:31:20.858019 [Info] [Mysterium.api] Total proposals: 1 supported: 1
01-28 13:31:20.859 15113 15280 I GoLog   : 2019-01-28T11:31:20.858304 [Info] [NATS.DialogEstablisher] Connecting to: market.Contact{Type:"nats/v1", Definition:discovery.ContactNATSV1{Topic:"0x56543ba36efe40
da000ee746cbe1dbfc4357331d.openvpn", BrokerAddresses:[]string{"nats://testnet-broker.mysterium.network:4222"}}}
01-28 13:31:20.979 15113 15225 I GoLog   : 2019-01-28T11:31:20.97728 [Debug] [NATS.Sender] Request '0x56543ba36efe40da000ee746cbe1dbfc4357331d.openvpn.dialog-create' sending: {"payload":{"peer_id":"0x869ec8
2817cc5df7e0a56be5bbf0476b08c12f20"},"signature":"8fagX0dsD3LawrxxjTFjirVsvqoXVPBAAZ/WucpcRKZ6MFwAOkO53WK2frvYWpzKYIv4Tl6LyQKB0MxxtQyY2wE="}
01-28 13:31:21.241 15113 15225 I GoLog   : 2019-01-28T11:31:21.241536 [Debug] [NATS.Sender] Received response for '0x56543ba36efe40da000ee746cbe1dbfc4357331d.openvpn.dialog-create': {"payload":{"reason":200
,"reasonMessage":"OK"},"signature":"/d32ZCT09XqHT4E+1uL4gbAlyh62sPp8vzHbD5qpyVIGQkNdVtu+kOYTXHHeTjehUwMSeSJ0PCZplEtHZ8idhgE="}
01-28 13:31:21.243 15113 15280 I GoLog   : 2019-01-28T11:31:21.242195 [Info] [NATS.DialogEstablisher] Dialog established with: market.Contact{Type:"nats/v1", Definition:discovery.ContactNATSV1{Topic:"0x5654
3ba36efe40da000ee746cbe1dbfc4357331d.openvpn", BrokerAddresses:[]string{"nats://testnet-broker.mysterium.network:4222"}}}
01-28 13:31:21.245 15113 15258 I GoLog   : 2019-01-28T11:31:21.243498 [Debug] [NATS.Sender] Request '0x56543ba36efe40da000ee746cbe1dbfc4357331d.openvpn.0x869ec82817cc5df7e0a56be5bbf0476b08c12f20.session-cre
ate' sending: {"payload":{"proposal_id":1,"config":null},"signature":"pauHHxtK3g1GrZbE9JnHec0xmUKOuRt8AU+A5lZCluUrxxI8XlmtxAKUaXqT5Gc0U/r8nqG8V5N4xAOFgWfPUQA="}
01-28 13:31:21.370 15113 15258 I GoLog   : 2019-01-28T11:31:21.369687 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:31:21.516 15113 15258 I GoLog   : 2019-01-28T11:31:21.514783 [Debug] [NATS.Sender] Received response for '0x56543ba36efe40da000ee746cbe1dbfc4357331d.openvpn.0x869ec82817cc5df7e0a56be5bbf0476b08c12f20.session-create': {"payload":{"success":true,"message":"","session":{"id":"7295b2c4-151a-404c-b0a3-4a5bfc5bfae1","config":{"remote":"191.252.109.164","port":1194,"protocol":"udp","TLSPresharedKey":"-----BEGIN OpenVPN Static key V1-----\nf80177a45194a3eb3a98c8cace485bd8880afec2706eca2257926309b974ced49d8883f2a8edbd0ffbb5e7ecafe52ee12c868e002e935553038f257157e146d3e5526bb772d4494c0ff45377a60ccf095eecbb99f3a40c8d5ace8586778bcf88e217660ba644764ad033c67835d40c3565b9ee316ead1e9c6091892f545c1e5466ef206b5fced1ef92efbce417650d5b66719034ff4e995ce54e5380d9f71f6154ec0307168601f243b2ec74781d12f5e01c228925c261ce97fc1414d8a73e7975bc1c656387eebbf97a45951ed3b0cb0b650754f462d660e5a41630dea30c868f7d1c98377e23221d62fd242b76d33fa97f73c06b4a63d70c8dd213197aa059\n-----END OpenVPN Static key V1-----\n","CACertificate":"-----BEGIN CERTIFICATE-----\nMIIBxzCCAWygAwIBAgICBFc
01-28 13:31:21.517 15113 15258 I GoLog   : wCgYIKoZIzj0EAwIwQjELMAkGA1UEBhMCQlIxGjAY\nBgNVBAoTEU15c3Rlcml1bSBOZXR3b3JrMRcwFQYDVQQLEw5NeXN0ZXJpdW0gVGVh\nbTAeFw0xOTAxMjUxMzI1MDFaFw0yOTAxMjUxMzI1MDFaMEIxCzAJBgNVBAYTAkJS\nMRowGAYDVQQKExFNeXN0ZXJpdW0gTmV0d29yazEXMBUGA1UECxMOTXlzdGVyaXVt\nIFRlYW0wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASsANzHK1/+bg5Xlm6h+ZmQ\nz9gd4PoVFDANb2OfcQ4e6aBVmJX4UXai8+pkukeor+MaE9lvqqkh17h4AZylwy1i\no1IwUDAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF\nBwMBMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0OBAcEBQECAwQFMAoGCCqGSM49BAMC\nA0kAMEYCIQDxkCTDv1hVqbkDgQMER68jfvi5pbFs5GvLoEehJaGUYwIhALzRGbYn\nyLVHTo0cqjU14Y9dKlmroYvvJUntmJuv2yix\n-----END CERTIFICATE-----\n"}}},"signature":"GVjjBbV2jJyATZ3uaKkoCIrkaf6n/Mi2nvrlxdGpwc1pVnfqpdszMqNCjDaz0U+1aq5KYVajWLq7H9QWx3n2ZgE="}
01-28 13:31:21.520 15113 15258 I GoLog   : 2019-01-28T11:31:21.51885 [Debug] [session-stats-sender] started
01-28 13:31:21.536 15113 15236 I GoLog   : 2019-01-28T11:31:21.534404 [Trace] [session-storage] Session 7295b2c4-151a-404c-b0a3-4a5bfc5bfae1 saved
01-28 13:31:30.590 15113 15225 I GoLog   : 2019-01-28T11:31:30.58831 [Info] [Mysterium.api] Total proposals: 80 supported: 80
01-28 13:31:31.591 15113 15225 I GoLog   : 2019-01-28T11:31:31.590588 [Info] [ipify.api] IP detected: 88.119.191.24
01-28 13:31:40.620 15113 15225 I GoLog   : 2019-01-28T11:31:40.61761 [Info] [Mysterium.api] Total proposals: 80 supported: 80
```

### PR DESCRIPTION
**Pull request by tadovas**
Closes #682
This was nasty

### CODE REVIEW

File: mobile/mysterium/openvpn_connection_setup.go [hunk 1]
```diff
@@ -73,6 +73,8 @@ func channelToCallbacks(stateChannel connection.StateChannel, statisticsChannel
 	}
 }
 
+const openvpn3Log = "[Openvpn3]"
```
Comment (zolia) [inline mobile/mysterium/openvpn_connection_setup.go]:
```suggestion
const openvpn3Log = "[Openvpn3] "
```
