### PR TITLE
Fix p2p msg envelope

### LINKED ISSUE #3901: Data corruption in service channel protocol
**Describe the bug**

It turns out, our transport messages (envelopes responsible for multiplexing different streams in one Channel) are serialized with net/textproto which is only suitable for text protocols. Due to its text nature, following distortions will occur:

- If message last byte is `0x0a`, it will be stripped.
- If message last byte is `0x0d`, it will be stripped.
- If message contains sequence `0x0d0a`, it will be replaced with `0x0a` byte.

Fuzzing experiment indicate that if message contains, for example, 65 bytes of uniformly distributed binary data (like sec256k1 ethereum signature), there is ~1% chance for message to arrive corrupted on the other end.

Also, as [noted in documentation](https://pkg.go.dev/net/textproto#NewReader) for "net/textproto" module, denial of service attack is possible if remote peer is able to exhaust node memory within time period limited by channel message read timeout.

**To Reproduce**

Run tests suggested by PR #3897.

**Expected behavior**

No data corruption/tests passing.

**Screenshots**

Spotted in the wild:

```
2021-08-31T05:16:32.936 DBG source/core/connection/manager.go:540    > Sending P2P message to "p2p-session-create": consumer:{id:"0x2959319983c1c2747d490493e212a974399fa832" hermesID:"0x7119442C7E627438deb0ec59291e31378F88DD06" paymentVersion:"v3" location:{country:"UA"} pricing:{PerGib:"ko\x178C\xbe\x0c" PerHour:"\x1b\x80ʍa6"}} config:"{\"PublicKey\":\"tzcs5Y5WngC/5shvqn5eGvgq10lUDR4pbHov30VuPSM=\",\"Ports\":null}"
2021-08-31T05:16:32.936 DBG source/session/pingpong/invoice_payer.go:127 > Starting...
2021-08-31T05:16:33.206 DBG source/session/pingpong/factory.go:136   > Received P2P message for "p2p-payment-invoice": AgreementID:"20908052794842088383280901706687126014545097939578838750221382806604748185440" AgreementTotal:"1" TransactorFee:"0" Hashlock:"2c32da0e37045846348784786232dccba8453893ec08220d0a2b4044c926a6fb" Provider:"0x0581aea5eea29b57d118a88a28d85df2b889f3c7" ChainID:80001
2021-08-31T05:16:33.206 DBG source/session/pingpong/invoice_payer.go:146 > Invoice received: {20908052794842088383280901706687126014545097939578838750221382806604748185440 1 0 2c32da0e37045846348784786232dccba8453893ec08220d0a2b4044c926a6fb 0x0581aea5eea29b57d118a88a28d85df2b889f3c7 80001}
2021-08-31T05:16:33.206 DBG source/session/pingpong/price_calculator.go:51 > Calculated price 590626630058486. Time component: 2.2545324162569456291e+09, data component: 5.906243755260702344e+14 
2021-08-31T05:16:33.213 DBG source/session/pingpong/invoice_payer.go:191 > Estimated tolerance 3, upper bound 1771879890175458
2021-08-31T05:16:33.213 DBG source/session/pingpong/invoice_payer.go:244 > Loaded previous state: already promised: 0
2021-08-31T05:16:33.213 DBG source/session/pingpong/invoice_payer.go:245 > Incrementing promised amount by 1
2021-08-31T05:16:33.214 DBG source/session/pingpong/exchange_messaging.go:68 > Sending P2P message to "p2p-payment-message": Promise:{ChannelID:"\x96\xd5\x18_\xeb~$\x96\xf2+\x12\x1dw+\xedg\xb4\x91\xde\x1b" Amount:"1" Fee:"0" Hashlock:",2\xda\x0e7\x04XF4\x87\x84xb2\xdc˨E8\x93\xec\x08\"\r\n+@D\xc9&\xa6\xfb" ChainID:80001 Signature:"x8-H\xa7zD\xcdqk\x14Kt,<\x91::\xd2\r\x10\x0fqc\xa50\xfen\xb3\xca\xed\xb9\\\x1a\x82\xf2R'\xa1\xb3\xd9Օ\x17\xacaM\xab\x07\xeb\xee+B\x9e\x071\x80K\xe9\xbb\x17{\xe5\xf1\x1c"} AgreementID:"20908052794842088383280901706687126014545097939578838750221382806604748185440" AgreementTotal:"1" Provider:"0x0581aea5eea29b57d118a88a28d85df2b889f3c7" Signature:"37df78105bde3a91ab1a020430f6e40e54ff51296508e353620953104de579df4fd85c4071cf822d50e40ea84e30f05587780364edf8e08e30bed2bbf3b365a51c" HermesID:"0x7119442C7E627438deb0ec59291e31378F88DD06" ChainID:80001
2021-08-31T05:16:33.279 WRN source/session/pingpong/invoice_payer.go:267 > Failed to send exchange message error="peer error: could not unmarshal exchange message proto: proto: cannot parse invalid wire-format data"
```

**Environment (please complete the following information):**
 - Node version: since 0.30.0-rc0 till current trunk
 - OS: any
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A

**Additional context**

Fix of this bug will require to change P2P message serialization format, rendering new protocol incompatible with old one. Therefore, new protocol must be negotiated out of band, with some additional attribute in providers' proposals.

**Fix implementation suggestions**

I suggest following action plan:

- [x] Refactor current p2p.transportMsg to be able use abstract interface in its `readFrom` and `writeTo` methods instead of use specific `conn *textproto.Reader` type. Take deserialization out of this object, make it one of implementations supporting this transportMsg deserialization interface.
- [x] Implement another deserialization with same interface, serializing and deserializing transportMsg using Protocol Buffers.
- [x] In providers proposals, bump `compatibility` level.
- [x] Extend P2P channel config sent by consumer with option indicating use of new deserializer.
- [x] On provider side, use new (de)serializer if P2P channel config has new option enabled.
- [x] On consumer side, use new (de)serializer if provider proposal has new compatibility level. Also enable new option in P2P config sent to provider.
- [x] It's desirable to extend E2E test suite to cover this cases in all combinations.

### PR DESCRIPTION
**Pull request by Snawoot**
Fix #3901.

Backwards-compatible solution. In future we'll need to disable compatibility=0 as it poses some security threat. Reasonable to do it with Mainnet release as it will be breaking for users either way.

### CODE REVIEW

File: p2p/message_test.go [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+			msg:        "msg4",
+			data:       []byte("data4"),
+		},
+		&transportMsg{
+			id:         5,
+			statusCode: 5,
+			topic:      "topic5",
+			msg:        "msg5",
+			data:       []byte("data5"),
+		},
```
Comment (soffokl) [inline p2p/message_test.go:112]:
```suggestion
		{
			id:         1,
			statusCode: 1,
			topic:      "topic1",
			msg:        "msg1",
			data:       []byte("data1"),
		},
		{
			id:         2,
			statusCode: 2,
			topic:      "topic2",
			msg:        "msg2",
			data:       []byte("data2"),
		},
		{
			id:         3,
			statusCode: 3,
			topic:      "topic3",
			msg:        "msg3",
			data:       []byte("data3"),
		},
		{
			id:         4,
			statusCode: 4,
			topic:      "topic4",
			msg:        "msg4",
			data:       []byte("data4"),
		},
		{
			id:         5,
			statusCode: 5,
			topic:      "topic5",
			msg:        "msg5",
			data:       []byte("data5"),
		},
```

File: p2p/message_test.go [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+		t.Fatalf("Can't write data into conn: %v", err)
+	}
+
+	var msg2 transportMsg
+	err = msg2.readFrom(conn2)
+	if err != nil {
+		t.Fatalf("Can't read data from conn2: %v", err)
+	}
+
+	if bytes.Compare(msg.data, msg2.data) != 0 {
```
Comment (soffokl) [inline p2p/message_test.go:61]: > S1004: should use !bytes.Equal(msg.data, msg2.data) instead (gosimple)
```suggestion
	if !bytes.Equal(msg.data, msg2.data) {
```

File: p2p/wireformat.go [hunk 3]
```diff
@@ -0,0 +1,232 @@
...
+	"google.golang.org/protobuf/proto"
+
+	"github.com/mysteriumnetwork/node/p2p/compat"
+	"github.com/mysteriumnetwork/node/pb"
+)
+
+const maxTransportMsgLen = 128 * 1024
+
+func init() {
+	// This is needed to initialise global common headers map state internally
```
Comment (soffokl) [inline p2p/wireformat.go:40]: Two of my spellcheckers suggest to use `z` 😂 :
```suggestion
	// This is needed to initialize global common headers map state internally
```

**Review by soffokl — APPROVED** [review]

**Review by tomasmik — APPROVED** [review]
