### PR TITLE
Don't execute Linux commands on mobile

### LINKED ISSUE #3437: Do not execute Linux commands on mobile
**Describe the bug**
Mobile app tries to use Linux commands 

```
2021-05-31T02:52:54.000 ERR app/utils/netutil/network.go:81 > Failed to delete route: 107.20.217.163 0.0.0.0 error="\"ip route delete 107.20.217.163 via 0.0.0.0\": exec: \"sudo\": executable file not found in $PATH output: : exec: \"sudo\": executable file not found in $PATH"
2021-05-31T02:52:54.000 INF app/utils/netutil/network.go:79 > Cleaning stale route: 116.202.100.246 0.0.0.0
2021-05-31T02:52:54.000 DBG app/utils/netutil/network_linux.go:42 > "ip route delete 116.202.100.246 via 0.0.0.0" output:

```

### PR DESCRIPTION
**Pull request by Zensey**
Resolves #3437

### CODE REVIEW

File: utils/netutil/network_android.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
+// +build android
+
+/*
+ * Copyright (C) 2020 The "MysteriumNetwork/node" Authors.
```
Comment (soffokl) [inline utils/netutil/network_android.go:4]:
```suggestion
 * Copyright (C) 2021 The "MysteriumNetwork/node" Authors.
```

**Review by soffokl — APPROVED** [review]

File: utils/netutil/network_android.go (hunk 1 above)
Comment (Zensey) [reply utils/netutil/network_android.go]: OK

**Comment by Zensey** [comment]
Connected to a couple of peers on debug build of this branch.
At least it works and `adb logcat -s GoLog` does not show this error.

**Review by tadaskay — APPROVED** [review]
