### PR TITLE
fix #3976

### LINKED ISSUE #3976: Second withdrawal fails
Withdrawing first time works fine, fails on the second attempt.

### PR DESCRIPTION
**Pull request by vkuznecovas**

### CODE REVIEW

File: session/pingpong/hermes_promise_settler.go [hunk 1]
```diff
@@ -721,24 +722,22 @@ func (aps *hermesPromiseSettler) generateAgreementID() *big.Int {
 	return new(big.Int).SetBytes(agreementID)
 }
 
-func (aps *hermesPromiseSettler) getWithdrawalAmountViaHermes(chainID int64, hermesID, identity common.Address) (*big.Int, error) {
+func (aps *hermesPromiseSettler) getHermesData(chainID int64, hermesID, identity common.Address) (ConsumerData, error) {
```
Comment (Snawoot) [inline session/pingpong/hermes_promise_settler.go:725]: Structure `ConsumerData` is quite large. Can't we operate with pointer to it?

**Review by Snawoot — CHANGES_REQUESTED** [review]
ConsumerData structure is quite large. Can't we operate with pointers

File: session/pingpong/hermes_promise_settler.go (hunk 1 above)
Comment (vkuznecovas) [reply session/pingpong/hermes_promise_settler.go]: Overoptimizing the very rare call, but we can. Done.

**Review by Snawoot — APPROVED** [review]

**Review by soffokl — APPROVED** [review]

**Review by tomasmik — APPROVED** [review]
