### PR TITLE
Fix discovery stopping issues

### LINKED ISSUE #1387: Interrupt not handled correctly with --experimental-identity-check
Steps to reproduce:

1) git checkout payment-v2-messaging
2) go build -o myst  cmd/mysterium_node/mysterium_node.go
3) ./myst --experiment-identity-check service noop --agreed-terms-and-conditions
4) wait for identity registration wait(in logs, the message appears as ```2019-10-31T12:45:30.883 INF core/discovery/discovery.go:238          > identity 0x3675bf99bc528b387ca64c48c65af214ac942394 not registered, delaying proposal registration until identity is registered```
4) ctrl + c 

What happens:
the process runs despite being sent an interrupt

What should happen:
the process should terminate gracefully

### PR DESCRIPTION
**Pull request by vkuznecovas**
Discovery stopping logic reworked, there should not be any more indefinite hangs

Closes #1387

### CODE REVIEW

File: core/discovery/discovery.go [hunk 1]
```diff
@@ -176,18 +170,24 @@ func (d *Discovery) stopLoop() {
...
-		registerEvent := <-registerEventChan
-		switch registerEvent {
-		case identity_registry.Registered:
-			log.Info().Msg("Identity registered, proceeding with proposal registration")
-			go d.eventPublisher.Publish(IdentityRegistrationTopic, d.ownIdentity)
-			d.changeStatus(RegisterProposal)
-		case identity_registry.Cancelled:
-			log.Info().Msg("Cancelled identity registration")
-			d.changeStatus(IdentityRegisterFailed)
+		defer func() {
```
Comment (anjmao) [inline core/discovery/discovery.go]: Could be `defer unsubscribe()`
