### PR TITLE
Run goimports with builder

### LINKED ISSUE #450: Goimports check do nothing since goimport is not installed for CI
We are missing `goimports` tool on the CI, but it succeeds somehow anyway. 

```
bin/check_goimports
bin/check_goimports: line 23: goimports: command not found
All files are compliant to goimports.
```

It should fail if required dependencies not found. 
Required dependencies should be installed before running it.

### PR DESCRIPTION
**Pull request by tadovas**
Closes #450 
Run check_goimports inside preinstalled builder container

### CODE REVIEW

**Comment by tadovas** [comment]
This looks really important, as I already found one go file which was not "goimported"

**Comment by tadovas** [comment]
@mysteriumnetwork/core @Waldz @soffokl  check this as priority

File: discovery/factory.go [hunk 1]
```diff
@@ -52,12 +52,12 @@ func NewService(
 	signerCreate identity.SignerFactory,
 ) *Discovery {
 	return &Discovery{
-		identityRegistry:            identityRegistry,
-		identityRegistration:        identityRegistration,
-		mysteriumClient:             mysteriumClient,
-		signerCreate:                signerCreate,
-		statusChan:                  make(chan Status),
-		status:                      StatusUndefined,
+		identityRegistry:     identityRegistry,
```
Comment (soffokl) [inline discovery/factory.go]: This was formatted by goimports in my system. Maybe we have some old version of goimports in the build image?

File: .travis.yml [hunk 2]
```diff
@@ -48,7 +48,7 @@ jobs:
     - script: bin/builder_run bin/check_golint
       name: "golint check"
 
-    - script: bin/check_goimports
+    - script: bin/builder_run bin/check_goimports
```
Comment (soffokl) [inline .travis.yml]: I'd try to avoid using extra pre-build images for simple task. 
Maybe it's better to do `go get goimports` instead of running it in extra docker container?

Comment (soffokl) [reply .travis.yml]: And looks like direct call works a bit faster on my system:
image

Comment (soffokl) [reply .travis.yml]: This ^ was not counting time for image downloading.

File: discovery/factory.go (hunk 1 above)
Comment (soffokl) [reply discovery/factory.go]: Found it, I was using old version from https://github.com/bradfitz/goimports

Comment (soffokl) [reply discovery/factory.go]: or not
sorry for these comments fall :(

File: .travis.yml (hunk 2 above)
Comment (tadovas) [reply .travis.yml]: Your points are absolutely valid, but:
1. It's not improvement or feature, its a hotfix - intention was to fix it asap with minimal effort as build functionality is currently broken
2. golint is also go getted inside builder and is run the same way, maybe we can get rid of this builder completely when migrating to go style CI
