### PR TITLE
win: fix wfp and reenable it

### LINKED ISSUE #3462: DNS leaks again
**Describe the bug**
DNS leaks again.
Reported by customer, also I can see the leaks on https://www.dnsleaktest.com/results.html and https://ipleak.net/ by myself.
(see screenshots).
Screenshot 2021-06-09 at 15 14 52
Screenshot 2021-06-09 at 15 12 12

Tried by myself with provider 0xd6d92aeacc071ee7411862286bd0996d1a60bc9c

Affected OS: Windows, Linux. Mac not affected.

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Windows, Linux, Mac, Windows

### PR DESCRIPTION
**Pull request by Snawoot**
Fix #3462

Revamps efforts of PR #3338. Previous attempt wasn't successful and lead to breakage of P2P channel. It happens because WFP code implemented in that change built with assumption there is single process which holds WG connection. But we need to allow direct traffic for user-mode process as well. For this reason I introduce another allow rule for myst.exe which matches traffic by it's WFP AppID.

Suggestions are welcome.

### CODE REVIEW

**Comment by Snawoot** [comment]
No leak:

Screenshot_win10-clean_2021-07-29_19:41:56

WFP rules applied:

Screenshot_win10-clean_2021-07-29_19:45:28

**Review by soffokl — APPROVED** [review]
🎉

**Review by vkuznecovas — APPROVED** [review]

File: supervisor/daemon/wireguard/wginterface/firewall/helpers.go [hunk 1]
```diff
@@ -147,3 +152,24 @@ func getCurrentProcessAppID() (*wtFwpByteBlob, error) {
...
 	return appID, nil
 }
+
+func getMystAppID() (*wtFwpByteBlob, error) {
+	currentFile, err := os.Executable()
+	if err != nil {
+		return nil, wrapErr(err)
+	}
+
+	currentFile = filepath.Join(filepath.Dir(currentFile), MYST_EXECUTABLE)
```
Comment (mdomasevicius) [inline supervisor/daemon/wireguard/wginterface/firewall/helpers.go:162]: Is this really the desired outcome?

image

Comment (Snawoot) [reply supervisor/daemon/wireguard/wginterface/firewall/helpers.go:162]: @mdomasevicius You've missed `filepath.Dir`

Comment (Snawoot) [reply supervisor/daemon/wireguard/wginterface/firewall/helpers.go:162]: @mdomasevicius https://play.golang.org/p/glK_ID7yTDJ

**Review by tomasmik — APPROVED** [review]

**Review by mdomasevicius — APPROVED** [review]
